### ISSUE TITLE
HTTPError after running the script

### ISSUE THREAD

**Issue by jrabensc** [Danesprite/todoist-org-mode#1]
Hi, thanks for this script. I just ran it and it gave me this error:

`python main.py xxx todoist.org`

`HTTPError: something is probably wrong with your API token`

Are you still supporting this script?

Thanks,
Johannes

**Comment by drmfinlay** [comment]
Hello @jrabensc,

Thanks for reporting this. Sorry for my late response. I wrote this many years ago and haven't used it since migrating from Todoist to Org mode. The reason for this error is that the Todoist web API has changed from verson 7 to [version 8](https://developer.todoist.com/sync/v8/) since then.

I'll see if I can update it to use the newer API. I should also have written it to display the actual HTTP error code and message.

**Comment by jrabensc** [comment]
No worries. I just came upon this script, wanted to check it out and noticed this error.

**Comment by drmfinlay** [comment]
If you're still interested in this, I have rewritten it now. It's not perfect, but I figured it was better than letting the old code continue to rot.

The HTTPError won't occur any more, so I am closing this issue.
